"""Standalone Narrative Expectation Graph generation via Gemini 3.1 Pro.

Takes a plot (from the Plot and Scenes Generation Module), scene manifests,
visual features (from the Feature Scanner), and a student profile as input,
and produces a NEG per scene. Completely independent from
plot_scene_generator.py.

When visual features are provided, the NEG is grounded in what is actually
visible in the generated images rather than relying solely on the plot
descriptions.
"""

from __future__ import annotations

import asyncio
import json
import logging
from typing import Any, Dict, List, Optional

from google import genai
from google.genai import types

from src.generation.prompts.neg_prompt import (
    NEG_SYSTEM_PROMPT,
    NEG_USER_PROMPT_TEMPLATE,
)
from src.generation.utils import extract_json, get_response_text
from src.models.feature_scan import FeatureScanResult
from src.models.neg import NEGGenerationResult, SceneNEG
from src.models.plot import PlotGenerationResult
from src.models.student_profile import StudentProfile

logger = logging.getLogger(__name__)

MODEL_ID = "gemini-3.1-pro-preview"

# Retry defaults
DEFAULT_MAX_RETRIES = 3
DEFAULT_INITIAL_DELAY = 1.0  # seconds
DEFAULT_MAX_DELAY = 30.0  # seconds


class NEGGenerationError(Exception):
    """Raised when NEG generation fails after all retries."""


def _build_user_prompt(
    plot: PlotGenerationResult,
    student_profile: Optional[StudentProfile],
    features: Optional[FeatureScanResult] = None,
) -> str:
    """Build the user prompt from plot, features, and student profile."""
    plot_json = json.dumps(
        [scene.model_dump() for scene in plot.plot],
        indent=2,
    )

    profile_str = "(new student — no history yet)"
    if student_profile and student_profile.total_utterances > 0:
        profile_str = student_profile.to_prompt_context()

    features_str = "(no visual feature scan available — use plot descriptions)"
    if features and features.scenes:
        features_str = json.dumps(
            [scene.model_dump() for scene in features.scenes],
            indent=2,
        )

    return NEG_USER_PROMPT_TEMPLATE.format(
        plot_json=plot_json,
        visual_features=features_str,
        student_profile=profile_str,
    )


def _validate_neg_response(
    data: Dict[str, Any],
    expected_scene_ids: List[str],
) -> NEGGenerationResult:
    """Validate the LLM response against the Pydantic models.

    Raises ValueError if validation fails.
    """
    result = NEGGenerationResult.model_validate(data)

    if not result.scenes:
        raise ValueError("NEG is empty — no scenes generated")

    # Check that each scene has waypoints
    for scene_neg in result.scenes:
        if not scene_neg.waypoints:
            raise ValueError(
                f"Scene {scene_neg.scene_id} has no waypoints"
            )

    # Check that all expected scenes are covered
    generated_ids = {s.scene_id for s in result.scenes}
    missing = set(expected_scene_ids) - generated_ids
    if missing:
        logger.warning(
            "[neg-gen] Missing NEG for scenes: %s", missing
        )

    return result


async def generate_neg(
    api_key: str,
    plot: PlotGenerationResult,
    student_profile: Optional[StudentProfile] = None,
    features: Optional[FeatureScanResult] = None,
    *,
    max_retries: int = DEFAULT_MAX_RETRIES,
    initial_delay: float = DEFAULT_INITIAL_DELAY,
    max_delay: float = DEFAULT_MAX_DELAY,
    temperature: float = 0.7,
    thinking_budget: int = 2048,
) -> NEGGenerationResult:
    """Generate a Narrative Expectation Graph for each scene in the plot.

    Makes a single LLM call to produce waypoints, expected relations,
    and anticipated traps for every scene, personalized to the student.

    When visual features are provided, waypoints and vocabulary are
    grounded in what is actually visible in the generated images.

    Args:
        api_key: Gemini API key.
        plot: The plot generated by the Plot and Scenes Generation Module.
        student_profile: The child's error profile, or None for new students.
        features: Visual feature scan from the Feature Scanner. When
            provided, the NEG is grounded in actual visual properties
            rather than plot descriptions alone.
        max_retries: Maximum number of retry attempts on failure.
        initial_delay: Initial backoff delay in seconds.
        max_delay: Maximum backoff delay in seconds.
        temperature: LLM temperature.
        thinking_budget: Token budget for thinking/reasoning.

    Returns:
        NEGGenerationResult containing a SceneNEG per scene.

    Raises:
        NEGGenerationError: If generation fails after all retries.
    """
    user_prompt = _build_user_prompt(plot, student_profile, features)
    expected_scene_ids = [s.scene_id for s in plot.plot]
    client = genai.Client(api_key=api_key)

    last_error: Optional[Exception] = None
    delay = initial_delay

    for attempt in range(1, max_retries + 1):
        try:
            logger.info(
                "[neg-gen] Attempt %d/%d: calling %s...",
                attempt,
                max_retries,
                MODEL_ID,
            )

            response = await client.aio.models.generate_content(
                model=MODEL_ID,
                contents=user_prompt,
                config=types.GenerateContentConfig(
                    system_instruction=NEG_SYSTEM_PROMPT,
                    thinking_config=types.ThinkingConfig(
                        thinking_budget=thinking_budget
                    ),
                    temperature=temperature,
                    response_mime_type="application/json",
                ),
            )

            raw_text = get_response_text(response)
            logger.info(
                "[neg-gen] Got response (%d chars), parsing JSON...",
                len(raw_text),
            )

            data = extract_json(raw_text)
            result = _validate_neg_response(data, expected_scene_ids)

            total_waypoints = sum(
                len(s.waypoints) for s in result.scenes
            )
            total_traps = sum(
                len(s.anticipated_traps) for s in result.scenes
            )
            logger.info(
                "[neg-gen] Success: %d scenes, %d waypoints, %d traps.",
                len(result.scenes),
                total_waypoints,
                total_traps,
            )
            return result

        except Exception as exc:
            last_error = exc
            logger.warning(
                "[neg-gen] Attempt %d/%d failed: %s: %s",
                attempt,
                max_retries,
                type(exc).__name__,
                exc,
            )

            if attempt < max_retries:
                logger.info("[neg-gen] Retrying in %.1f seconds...", delay)
                await asyncio.sleep(delay)
                delay = min(delay * 2, max_delay)

    raise NEGGenerationError(
        f"NEG generation failed after {max_retries} attempts. "
        f"Last error: {last_error}"
    ) from last_error
